//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula5.TunaGreen.SqlServerRepository
{
    using System;
    
    public partial class SmallCar
    {
        public int ID { get; set; }
        public string Model { get; set; }
    }
}
