// <auto-generated />
namespace Aula5.TunaGreen.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Versione2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versione2));
        
        string IMigrationMetadata.Id
        {
            get { return "201807201427139_Versione2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
